### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [Evan-Med/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Evan-Med** [comment]
Hey there Mikey, I think I figured it out. It definitely looks different now when I open the webpage on my phone. 

Hope this is the fix you were looking for, thank you for your help!

**Comment by Mikeysax** [comment]
Nice job :+1:
